# Homepage top-of-page info widgets.
- resources:
    label: Pi 5 (.230)
    cpu: true
    memory: true
    cputemp: true
    tempmin: 0
    tempmax: 90
    uptime: true
    disk: /

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: short
